global with sharing class SlateApplication {

    public String SlateID;
    public String CSUID;
    public String Name;
    public String Term;
    public String AppStatus;
    public String CurrentProgram;
    public String CurrentProgramCode;
    public String CurrentSiteCode;
    public String Decision;
    public String MissingChecklistItems;
    public String FulfilledChecklistItems;
    public String Email1;
    public String Email2;
    public String Email3;
    public String Credits;
    public String OfficialGPA;
    public String CreatedDate;

}